TECH_EO_EXCESS_INPUT = {"risk_model_id": 278, "technology_liability_limit": 1000000, "technology_liability_retention": 1000000,
                        "technology_liability_exposure_modifier": 1, "technology_liability_probability_modifier": 1.15,
                        "technology_liability_pop_percentage": None, "information_privacy_limit": 1000000,
                        "information_privacy_retention": 1000000, "information_privacy_exposure_modifier": 0.51,
                        "information_privacy_probability_modifier": 1.14, "information_privacy_pop_percentage": None,
                        "information_privacy_liability_limit": 1000000, "information_privacy_liability_retention": 1000000,
                        "information_privacy_liability_exposure_modifier": 0.51,
                        "information_privacy_liability_probability_modifier": 1.14,
                        "information_privacy_liability_pop_percentage": None, "regulatory_liability_limit": 1000000,
                        "regulatory_liability_retention": 1000000, "regulatory_liability_exposure_modifier": None,
                        "regulatory_liability_probability_modifier": None, "regulatory_liability_pop_percentage": None,
                        "event_response_and_management_limit": 1000000, "event_response_and_management_retention": 1000000,
                        "event_response_and_management_exposure_modifier": None,
                        "event_response_and_management_probability_modifier": None,
                        "event_response_and_management_pop_percentage": None, "pci_dss_liability_limit": 1000000,
                        "pci_dss_liability_retention": 1000000, "pci_dss_liability_exposure_modifier": None,
                        "pci_dss_liability_probability_modifier": None, "pci_dss_liability_pop_percentage": None,
                        "network_security_limit": 1000000, "network_security_retention": 1000000,
                        "network_security_exposure_modifier": 0.75, "network_security_probability_modifier": 1.01,
                        "network_security_pop_percentage": None, "network_security_liability_limit": 1000000,
                        "network_security_liability_retention": 1000000, "network_security_liability_exposure_modifier": 0.75,
                        "network_security_liability_probability_modifier": 1.01, "network_security_liability_pop_percentage": None,
                        "event_response_and_recovery_limit": 1000000, "event_response_and_recovery_retention": 1000000,
                        "event_response_and_recovery_exposure_modifier": None,
                        "event_response_and_recovery_probability_modifier": None, "event_response_and_recovery_pop_percentage": None,
                        "business_interruption_limit": 1000000, "business_interruption_retention": 1000000,
                        "business_interruption_exposure_modifier": 1, "business_interruption_probability_modifier": 0.9,
                        "business_interruption_pop_percentage": None, "direct_business_interruption_limit": 1000000,
                        "direct_business_interruption_retention": 1000000, "direct_business_interruption_exposure_modifier": 1,
                        "direct_business_interruption_probability_modifier": 0.9, "direct_business_interruption_pop_percentage": None,
                        "contingent_business_interruption_limit": 1000000, "contingent_business_interruption_retention": 1000000,
                        "contingent_business_interruption_exposure_modifier": None,
                        "contingent_business_interruption_probability_modifier": None,
                        "contingent_business_interruption_pop_percentage": None, "system_failure_limit": 1000000,
                        "system_failure_retention": 1000000, "system_failure_exposure_modifier": 1,
                        "system_failure_probability_modifier": 0.85, "system_failure_pop_percentage": None,
                        "system_failure_waiting_period_parameter": 8, "direct_system_failure_limit": 1000000,
                        "direct_system_failure_retention": 1000000, "direct_system_failure_exposure_modifier": 1,
                        "direct_system_failure_probability_modifier": 0.85, "direct_system_failure_pop_percentage": None,
                        "direct_system_failure_waiting_period_parameter": 8, "contingent_system_failure_limit": 1000000,
                        "contingent_system_failure_retention": 1000000, "contingent_system_failure_exposure_modifier": None,
                        "contingent_system_failure_probability_modifier": None, "contingent_system_failure_pop_percentage": None,
                        "cyber_extortion_limit": 1000000, "cyber_extortion_retention": 1000000, "cyber_extortion_exposure_modifier": 1,
                        "cyber_extortion_probability_modifier": 0.87, "cyber_extortion_pop_percentage": None,
                        "financial_fraud_limit": 250000, "financial_fraud_retention": 10000, "financial_fraud_exposure_modifier": 1,
                        "financial_fraud_probability_modifier": 0.87, "financial_fraud_pop_percentage": None,
                        "social_engineering_limit": 250000, "social_engineering_retention": 10000,
                        "social_engineering_exposure_modifier": 1, "social_engineering_probability_modifier": 0.87,
                        "social_engineering_pop_percentage": None, "computer_fraud_limit": 250000, "computer_fraud_retention": 10000,
                        "computer_fraud_exposure_modifier": None, "computer_fraud_probability_modifier": None,
                        "computer_fraud_pop_percentage": None, "media_content_limit": 1000000, "media_content_retention": 1000000,
                        "media_content_exposure_modifier": 1, "media_content_probability_modifier": 1.23,
                        "media_content_pop_percentage": None, "media_liability_limit": 1000000, "media_liability_retention": 1000000,
                        "media_liability_exposure_modifier": 1, "media_liability_probability_modifier": 1.23,
                        "media_liability_pop_percentage": None, "media_event_response_limit": 1000000,
                        "media_event_response_retention": 1000000, "media_event_response_exposure_modifier": None,
                        "media_event_response_probability_modifier": None, "media_event_response_pop_percentage": None,
                        "reputational_harm_limit": 1000000, "reputational_harm_retention": 10000,
                        "reputational_harm_exposure_modifier": 1.1, "reputational_harm_probability_modifier": None,
                        "reputational_harm_pop_percentage": None, "reputational_harm_period_of_indemnity_parameter": 180,
                        "excess_coverage_limit": 1000000, "excess_coverage_retention": 2000000,
                        "excess_coverage_exposure_modifier": None, "excess_coverage_probability_modifier": None,
                        "excess_coverage_pop_percentage": None, "CA1": None, "CA10": None, "CA12": None, "CA13": None, "CA15": None,
                        "CA17": None, "CA19": None, "CA2": None, "CA20": None, "CA21": None, "CA22": None, "CA24": None, "CA25": None,
                        "CA26": None, "CA28": None, "CA29": None, "CA3": None, "CA30": None, "CA31": None, "CA4": None, "CA5": None,
                        "CA6": None, "CA7": None, "CA8": None, "Ex1": 0, "Ex21": 0, "Ex22": 1, "Ex23": 1, "Ex24": 1, "Ex25": 8,
                        "Ex28": 0, "Ex31": None, "Ex32": 8, "Ex33": 0, "Ex34": 0, "Ex35": 0, "Ex36": 0, "Ex37": 0, "Ex38": 0,
                        "Ex39": 0, "Ex40": 0, "Ex41": 0, "Ex42": 0, "Ex43": 0, "Ex44": 0, "Ex45": 0, "Ex51": 0, "Ex52": 0, "Ex53": 0,
                        "Ex54": 0, "Ex55": 0, "Ex56": 236, "Ex57": 0, "Ex58": 0, "Ex59": True, "TEO_UW1": None, "TEO_UW10": None,
                        "TEO_UW11": None, "TEO_UW12": None, "TEO_UW13": None, "TEO_UW14": None, "TEO_UW16": None, "TEO_UW17": None,
                        "TEO_UW2": None, "TEO_UW3": None, "TEO_UW7": None, "UW40": None, "UW41": None, "UW42": None, "UW44": None,
                        "UW50": None, "UW51": None, "UW52": None, "UW53": None, "UW54": None, "UW55": None, "UW56": None, "UW57": None,
                        "UW58": None, "UW59": None, "UW60": None, "UW61": None, "UW62": None, "UW63": None, "UW64": None, "UW65": None,
                        "UW66": None, "UW67": None, "UW68": None, "UW69": None, "UW70": None, "UW71": None, "UW72": None, "UW73": None,
                        "UW74": None, "UW75": None, "Q2119": None, "Q2124": None, "Q2135": "shany_tech_excess", "Q2136": 5000000,
                        "Q2137": "hava.com", "Q2138": "Technology", "Q2139": None, "Q2141": True, "Q2142": True, "Q2143": True,
                        "Q2146": False, "Q2147": False, "Q2159": False, "Q2162": None,
                        "Q2163": "{\"formatted_address\": \"196 Castro St, Mountain View, CA 94041, USA\"}", "Q2164": None,
                        "Q2204_C1361": True, "Q2204_C1362": False, "Q2204_C1404": False, "Q2205": True, "Q2206": "Never",
                        "Q2207": 10000, "Q2208_C1421": False, "Q2208_C1422": False, "Q2208_C1424": False, "Q2208_C1425": False,
                        "Q2208_C1426": False, "Q2208_C1476": False, "Q2208_C1485": False, "Q2208_C1513": False, "Q2208_C1514": False,
                        "Q2208_NONE_OF_THE_ABOVE": True, "Q2210_C1378": True, "Q2210_C1405": False, "Q2218": True,
                        "Q2219_C1399": False, "Q2219_C1400": False, "Q2219_C1401": False, "Q2219_C1402": False, "Q2219_C1403": False,
                        "Q2219_NONE_OF_THE_ABOVE": True, "Q2220": None, "Q2226_C1490": False, "Q2226_C1491": False,
                        "Q2226_C1492": False, "Q2226_C1493": False, "Q2226_C1494": False, "Q2226_C1495": False, "Q2226_C1496": False,
                        "Q2226_C1497": False, "Q2226_C1515": False, "Q2226_NONE_OF_THE_ABOVE": True, "Q2228": None, "Q2229": True,
                        "Q2230": "Not applicable", "Q2233": None, "Q2235": None, "Q2236": None, "Q2237": None, "Q2238": None,
                        "Q2239": None, "Q2240": None, "Q2245": True,
                        "excess_layers": [{"limit": 1000000, "premium": 1000000, "retention": 100000},
                                          {"limit": 1000000, "premium": 1000000}]}

TECH_EO_INPUT = {"risk_model_id": 276, "technology_liability_limit": 1000000, "technology_liability_retention": 10000,
                 "technology_liability_exposure_modifier": 1, "technology_liability_probability_modifier": 1.05,
                 "technology_liability_pop_percentage": None, "information_privacy_limit": 1000000,
                 "information_privacy_retention": 10000, "information_privacy_exposure_modifier": 0.51,
                 "information_privacy_probability_modifier": 1.1, "information_privacy_pop_percentage": None,
                 "information_privacy_liability_limit": 1000000, "information_privacy_liability_retention": 10000,
                 "information_privacy_liability_exposure_modifier": 0.51, "information_privacy_liability_probability_modifier": 1.1,
                 "information_privacy_liability_pop_percentage": None, "regulatory_liability_limit": 1000000,
                 "regulatory_liability_retention": 10000, "regulatory_liability_exposure_modifier": None,
                 "regulatory_liability_probability_modifier": None, "regulatory_liability_pop_percentage": None,
                 "event_response_and_management_limit": 1000000, "event_response_and_management_retention": 10000,
                 "event_response_and_management_exposure_modifier": None, "event_response_and_management_probability_modifier": None,
                 "event_response_and_management_pop_percentage": None, "pci_dss_liability_limit": 1000000,
                 "pci_dss_liability_retention": 10000, "pci_dss_liability_exposure_modifier": None,
                 "pci_dss_liability_probability_modifier": None, "pci_dss_liability_pop_percentage": None,
                 "network_security_limit": 1000000, "network_security_retention": 10000, "network_security_exposure_modifier": 0.63,
                 "network_security_probability_modifier": 1.01, "network_security_pop_percentage": None,
                 "network_security_liability_limit": 1000000, "network_security_liability_retention": 10000,
                 "network_security_liability_exposure_modifier": 0.63, "network_security_liability_probability_modifier": 1.01,
                 "network_security_liability_pop_percentage": None, "event_response_and_recovery_limit": 1000000,
                 "event_response_and_recovery_retention": 10000, "event_response_and_recovery_exposure_modifier": None,
                 "event_response_and_recovery_probability_modifier": None, "event_response_and_recovery_pop_percentage": None,
                 "business_interruption_limit": 1000000, "business_interruption_retention": 10000,
                 "business_interruption_exposure_modifier": 1, "business_interruption_probability_modifier": 0.83,
                 "business_interruption_pop_percentage": None, "direct_business_interruption_limit": 1000000,
                 "direct_business_interruption_retention": 10000, "direct_business_interruption_exposure_modifier": 1,
                 "direct_business_interruption_probability_modifier": 0.83, "direct_business_interruption_pop_percentage": None,
                 "contingent_business_interruption_limit": 1000000, "contingent_business_interruption_retention": 10000,
                 "contingent_business_interruption_exposure_modifier": None,
                 "contingent_business_interruption_probability_modifier": None,
                 "contingent_business_interruption_pop_percentage": None, "system_failure_limit": 1000000,
                 "system_failure_retention": 10000, "system_failure_exposure_modifier": 1, "system_failure_probability_modifier": 0.85,
                 "system_failure_pop_percentage": None, "system_failure_waiting_period_parameter": 8,
                 "direct_system_failure_limit": 1000000, "direct_system_failure_retention": 10000,
                 "direct_system_failure_exposure_modifier": 1, "direct_system_failure_probability_modifier": 0.85,
                 "direct_system_failure_pop_percentage": None, "direct_system_failure_waiting_period_parameter": 8,
                 "contingent_system_failure_limit": 1000000, "contingent_system_failure_retention": 10000,
                 "contingent_system_failure_exposure_modifier": None, "contingent_system_failure_probability_modifier": None,
                 "contingent_system_failure_pop_percentage": None, "cyber_extortion_limit": 1000000,
                 "cyber_extortion_retention": 10000, "cyber_extortion_exposure_modifier": 1,
                 "cyber_extortion_probability_modifier": 0.81, "cyber_extortion_pop_percentage": None,
                 "financial_fraud_limit": 1000000, "financial_fraud_retention": 10000, "financial_fraud_exposure_modifier": 1,
                 "financial_fraud_probability_modifier": 1.41, "financial_fraud_pop_percentage": None,
                 "social_engineering_limit": 1000000, "social_engineering_retention": 10000, "social_engineering_exposure_modifier": 1,
                 "social_engineering_probability_modifier": 1.41, "social_engineering_pop_percentage": None,
                 "computer_fraud_limit": 1000000, "computer_fraud_retention": 10000, "computer_fraud_exposure_modifier": None,
                 "computer_fraud_probability_modifier": None, "computer_fraud_pop_percentage": None, "media_content_limit": 1000000,
                 "media_content_retention": 10000, "media_content_exposure_modifier": 1, "media_content_probability_modifier": 1.18,
                 "media_content_pop_percentage": None, "media_liability_limit": 1000000, "media_liability_retention": 10000,
                 "media_liability_exposure_modifier": 1, "media_liability_probability_modifier": 1.18,
                 "media_liability_pop_percentage": None, "media_event_response_limit": 1000000,
                 "media_event_response_retention": 10000, "media_event_response_exposure_modifier": None,
                 "media_event_response_probability_modifier": None, "media_event_response_pop_percentage": None,
                 "reputational_harm_limit": 1000000, "reputational_harm_retention": 10000, "reputational_harm_exposure_modifier": 1.1,
                 "reputational_harm_probability_modifier": None, "reputational_harm_pop_percentage": None,
                 "reputational_harm_period_of_indemnity_parameter": 180, "commercial_consideration": 1,
                 "operational_considerations": 0.9, "prior_acts_coverage": 1, "per_claim_limit": 1000000, "CA1": None, "CA10": None,
                 "CA12": None, "CA13": None, "CA15": None, "CA17": None, "CA19": None, "CA2": None, "CA20": None, "CA21": None,
                 "CA22": None, "CA24": None, "CA25": None, "CA26": None, "CA28": None, "CA29": None, "CA3": None, "CA30": None,
                 "CA31": None, "CA4": None, "CA5": None, "CA6": None, "CA7": None, "CA8": None, "Ex1": 0, "Ex21": 0, "Ex22": 1,
                 "Ex23": 1, "Ex24": 2, "Ex25": 1, "Ex28": 0, "Ex31": None, "Ex32": 1, "Ex33": 0, "Ex34": 0, "Ex35": 0, "Ex36": 0,
                 "Ex37": 0, "Ex38": 0, "Ex39": 0, "Ex40": 0, "Ex41": 0, "Ex42": 0, "Ex43": 0, "Ex44": 0, "Ex45": 0, "Ex51": 0,
                 "Ex52": 0, "Ex53": 0, "Ex54": 0, "Ex55": 0, "Ex56": 230, "Ex57": 0, "Ex58": 0, "Ex59": True,
                 "TEO_UW1": "Business Software Cybersecurity Software to businesses ", "TEO_UW10": None, "TEO_UW11": None,
                 "TEO_UW12": None, "TEO_UW13": None, "TEO_UW14": None, "TEO_UW16": None, "TEO_UW17": None, "TEO_UW2": None,
                 "TEO_UW3": None, "TEO_UW7": None, "UW40": None, "UW41": None, "UW42": None, "UW44": None, "UW50": None, "UW51": None,
                 "UW52": None, "UW53": None, "UW54": None, "UW55": None, "UW56": None, "UW57": None, "UW58": None, "UW59": None,
                 "UW60": None, "UW61": None, "UW62": None, "UW63": None, "UW64": None, "UW65": None, "UW66": None, "UW67": None,
                 "UW68": None, "UW69": None, "UW70": None, "UW71": None, "UW72": None, "UW73": None, "UW74": None, "UW75": None,
                 "Q2119": None, "Q2124": None, "Q2135": "Test Tech E&O", "Q2136": 27000000, "Q2137": "stam.com", "Q2138": "Technology",
                 "Q2139": None, "Q2141": False, "Q2142": True, "Q2143": True, "Q2146": False, "Q2147": False, "Q2159": False,
                 "Q2162": None,
                 "Q2163": "{\"formatted_address\": \"2 Main St, Brooklyn, NY 11201, \\u05d0\\u05e8\\u05e6\\u05d5\\u05ea \\u05d4\\u05d1\\u05e8\\u05d9\\u05ea\"}",
                 "Q2164": None, "Q2204_C1361": False, "Q2204_C1362": False, "Q2204_C1404": True, "Q2205": True, "Q2206": "Always",
                 "Q2207": 30000, "Q2209_C1371": False, "Q2209_C1454": False, "Q2209_C1458": False, "Q2209_C1460": False,
                 "Q2209_C1498": False, "Q2209_C1499": False, "Q2209_C1500": False, "Q2209_C1501": False, "Q2209_C1502": False,
                 "Q2209_C1503": False, "Q2209_C1508": False, "Q2209_NONE_OF_THE_ABOVE": True, "Q2210_C1378": False,
                 "Q2210_C1405": True, "Q2218": False, "Q2219_C1399": False, "Q2219_C1400": False, "Q2219_C1401": False,
                 "Q2219_C1402": False, "Q2219_C1403": False, "Q2219_NONE_OF_THE_ABOVE": True, "Q2220": None, "Q2226_C1490": False,
                 "Q2226_C1491": False, "Q2226_C1492": False, "Q2226_C1493": False, "Q2226_C1494": False, "Q2226_C1495": False,
                 "Q2226_C1496": False, "Q2226_C1497": False, "Q2226_C1515": False, "Q2226_NONE_OF_THE_ABOVE": True, "Q2228": None,
                 "Q2229": False, "Q2230": "Yes", "Q2233": None, "Q2235": None, "Q2236": None, "Q2237": None, "Q2238": True,
                 "Q2239": None, "Q2240": None, "Q2245": True}

CYBER_EXCESS_INPUT = {"risk_model_id": 277, "information_privacy_limit": 1000000, "information_privacy_retention": 1000000,
                      "information_privacy_exposure_modifier": 0.25, "information_privacy_probability_modifier": 1.17,
                      "information_privacy_pop_percentage": None, "information_privacy_liability_limit": 1000000,
                      "information_privacy_liability_retention": 1000000, "information_privacy_liability_exposure_modifier": 0.25,
                      "information_privacy_liability_probability_modifier": 1.17, "information_privacy_liability_pop_percentage": None,
                      "regulatory_liability_limit": 1000000, "regulatory_liability_retention": 1000000,
                      "regulatory_liability_exposure_modifier": None, "regulatory_liability_probability_modifier": None,
                      "regulatory_liability_pop_percentage": None, "event_response_and_management_limit": 1000000,
                      "event_response_and_management_retention": 1000000, "event_response_and_management_exposure_modifier": None,
                      "event_response_and_management_probability_modifier": None, "event_response_and_management_pop_percentage": None,
                      "pci_dss_liability_limit": 1000000, "pci_dss_liability_retention": 1000000,
                      "pci_dss_liability_exposure_modifier": None,
                      "pci_dss_liability_probability_modifier": None, "pci_dss_liability_pop_percentage": None,
                      "network_security_limit": 1000000, "network_security_retention": 1000000,
                      "network_security_exposure_modifier": 1.01,
                      "network_security_probability_modifier": 1.01, "network_security_pop_percentage": None,
                      "network_security_liability_limit": 1000000, "network_security_liability_retention": 1000000,
                      "network_security_liability_exposure_modifier": 1.01, "network_security_liability_probability_modifier": 1.01,
                      "network_security_liability_pop_percentage": None, "event_response_and_recovery_limit": 1000000,
                      "event_response_and_recovery_retention": 1000000, "event_response_and_recovery_exposure_modifier": None,
                      "event_response_and_recovery_probability_modifier": None, "event_response_and_recovery_pop_percentage": None,
                      "business_interruption_limit": 1000000, "business_interruption_retention": 1000000,
                      "business_interruption_exposure_modifier": 0.5, "business_interruption_probability_modifier": 1.01,
                      "business_interruption_pop_percentage": None, "direct_business_interruption_limit": 1000000,
                      "direct_business_interruption_retention": 1000000, "direct_business_interruption_exposure_modifier": 0.5,
                      "direct_business_interruption_probability_modifier": 1.01, "direct_business_interruption_pop_percentage": None,
                      "contingent_business_interruption_limit": 1000000, "contingent_business_interruption_retention": 1000000,
                      "contingent_business_interruption_exposure_modifier": None,
                      "contingent_business_interruption_probability_modifier": None,
                      "contingent_business_interruption_pop_percentage": None,
                      "system_failure_limit": 1000000, "system_failure_retention": 1000000, "system_failure_exposure_modifier": 0.5,
                      "system_failure_probability_modifier": 0.85, "system_failure_pop_percentage": None,
                      "system_failure_waiting_period_parameter": 8, "direct_system_failure_limit": 1000000,
                      "direct_system_failure_retention": 1000000, "direct_system_failure_exposure_modifier": 0.5,
                      "direct_system_failure_probability_modifier": 0.85, "direct_system_failure_pop_percentage": None,
                      "direct_system_failure_waiting_period_parameter": 8, "contingent_system_failure_limit": 1000000,
                      "contingent_system_failure_retention": 1000000, "contingent_system_failure_exposure_modifier": None,
                      "contingent_system_failure_probability_modifier": None, "contingent_system_failure_pop_percentage": None,
                      "cyber_extortion_limit": 1000000, "cyber_extortion_retention": 1000000, "cyber_extortion_exposure_modifier": 0.5,
                      "cyber_extortion_probability_modifier": 0.93, "cyber_extortion_pop_percentage": None,
                      "financial_fraud_limit": 250000,
                      "financial_fraud_retention": 10000, "financial_fraud_exposure_modifier": 0.77,
                      "financial_fraud_probability_modifier": 0.89, "financial_fraud_pop_percentage": None,
                      "social_engineering_limit": 250000, "social_engineering_retention": 10000,
                      "social_engineering_exposure_modifier": 0.77,
                      "social_engineering_probability_modifier": 0.89, "social_engineering_pop_percentage": None,
                      "computer_fraud_limit": 250000, "computer_fraud_retention": 10000, "computer_fraud_exposure_modifier": None,
                      "computer_fraud_probability_modifier": None, "computer_fraud_pop_percentage": None,
                      "media_content_limit": 1000000,
                      "media_content_retention": 1000000, "media_content_exposure_modifier": 0.77,
                      "media_content_probability_modifier": 1.26,
                      "media_content_pop_percentage": None, "media_liability_limit": 1000000, "media_liability_retention": 1000000,
                      "media_liability_exposure_modifier": 0.77, "media_liability_probability_modifier": 1.26,
                      "media_liability_pop_percentage": None, "media_event_response_limit": 1000000,
                      "media_event_response_retention": 1000000, "media_event_response_exposure_modifier": None,
                      "media_event_response_probability_modifier": None, "media_event_response_pop_percentage": None,
                      "reputational_harm_limit": 1000000, "reputational_harm_retention": 10000,
                      "reputational_harm_exposure_modifier": 0.5,
                      "reputational_harm_probability_modifier": None, "reputational_harm_pop_percentage": None,
                      "reputational_harm_period_of_indemnity_parameter": 180, "excess_coverage_limit": 2000000,
                      "excess_coverage_retention": 2000000, "excess_coverage_exposure_modifier": None,
                      "excess_coverage_probability_modifier": None, "excess_coverage_pop_percentage": None, "CA1": None, "CA10": None,
                      "CA12": None, "CA13": None, "CA15": None, "CA17": None, "CA19": None, "CA2": None, "CA20": None, "CA21": None,
                      "CA22": None, "CA24": None, "CA25": None, "CA26": None, "CA28": None, "CA29": None, "CA3": None, "CA30": None,
                      "CA31": None, "CA4": None, "CA5": None, "CA6": None, "CA7": None, "CA8": None, "Ex1": 0, "Ex21": 0, "Ex22": 1,
                      "Ex23": 7, "Ex24": 15, "Ex25": 1, "Ex28": 0, "Ex31": None, "Ex32": 1, "Ex33": 0, "Ex34": 0, "Ex35": 0, "Ex36": 0,
                      "Ex37": 0, "Ex38": 0, "Ex39": 0, "Ex40": 0, "Ex41": 0, "Ex42": 0, "Ex43": 0, "Ex44": 0, "Ex45": 0, "Ex51": 0,
                      "Ex52": 0,
                      "Ex53": 0, "Ex54": 0, "Ex55": 0, "Ex56": 236, "Ex57": 0, "Ex58": 0, "Ex59": True, "UW40": None, "UW41": None,
                      "UW42": None, "UW44": None, "UW50": None, "UW51": None, "UW52": None, "UW53": None, "UW54": None, "UW55": None,
                      "UW56": None, "UW57": None, "UW58": None, "UW59": None, "UW60": None, "UW61": None, "UW62": None, "UW63": None,
                      "UW64": None, "UW65": None, "UW66": None, "UW67": None, "UW68": None, "UW69": None, "UW70": None, "UW71": None,
                      "UW72": None, "UW73": None, "UW74": None, "UW75": None, "Q2119": None, "Q2124": None,
                      "Q2135": "shany_test__cyber_excess", "Q2136": 5000000, "Q2137": "hcva.com", "Q2138": "Construction",
                      "Q2140": None,
                      "Q2141": True, "Q2142": True, "Q2143": True, "Q2146": False, "Q2147": False, "Q2159": False, "Q2162": None,
                      "Q2163": "{\"formatted_address\": \"196 Castro St, Mountain View, CA 94041, USA\"}", "Q2164": None,
                      "Q2231": None,
                      "Q2232": None, "Q2233": None, "Q2234": None, "Q2236": None, "Q2237": None, "Q2244_C1576": False,
                      "Q2244_C1577": False,
                      "Q2244_C1578": False, "Q2244_C1579": False, "Q2244_C1580": False, "Q2244_C1581": False, "Q2244_C1582": False,
                      "Q2244_NONE_OF_THE_ABOVE": True, "Q2245": True,
                      "excess_layers": [{"limit": 1000000, "premium": 1000000, "retention": 100000},
                                        {"limit": 1000000, "premium": 1000000}]}

CYBER_INPUT = {"risk_model_id": 274, "information_privacy_limit": 2000000, "information_privacy_retention": 5000,
               "information_privacy_exposure_modifier": 1.84, "information_privacy_probability_modifier": 1.05,
               "information_privacy_pop_percentage": None, "information_privacy_liability_limit": 2000000,
               "information_privacy_liability_retention": 5000, "information_privacy_liability_exposure_modifier": 1.84,
               "information_privacy_liability_probability_modifier": 1.05, "information_privacy_liability_pop_percentage": None,
               "regulatory_liability_limit": 2000000, "regulatory_liability_retention": 5000,
               "regulatory_liability_exposure_modifier": None, "regulatory_liability_probability_modifier": None,
               "regulatory_liability_pop_percentage": None, "event_response_and_management_limit": 2000000,
               "event_response_and_management_retention": 5000, "event_response_and_management_exposure_modifier": None,
               "event_response_and_management_probability_modifier": None, "event_response_and_management_pop_percentage": None,
               "pci_dss_liability_limit": 2000000, "pci_dss_liability_retention": 5000, "pci_dss_liability_exposure_modifier": None,
               "pci_dss_liability_probability_modifier": None, "pci_dss_liability_pop_percentage": None,
               "network_security_limit": 2000000, "network_security_retention": 5000, "network_security_exposure_modifier": 1.26,
               "network_security_probability_modifier": 0.98, "network_security_pop_percentage": None,
               "network_security_liability_limit": 2000000, "network_security_liability_retention": 5000,
               "network_security_liability_exposure_modifier": 1.26, "network_security_liability_probability_modifier": 0.98,
               "network_security_liability_pop_percentage": None, "event_response_and_recovery_limit": 2000000,
               "event_response_and_recovery_retention": 5000, "event_response_and_recovery_exposure_modifier": None,
               "event_response_and_recovery_probability_modifier": None, "event_response_and_recovery_pop_percentage": None,
               "business_interruption_limit": 2000000, "business_interruption_retention": 5000,
               "business_interruption_exposure_modifier": 0.94, "business_interruption_probability_modifier": 1.11,
               "business_interruption_pop_percentage": None, "direct_business_interruption_limit": 2000000,
               "direct_business_interruption_retention": 5000, "direct_business_interruption_exposure_modifier": 0.94,
               "direct_business_interruption_probability_modifier": 1.11, "direct_business_interruption_pop_percentage": None,
               "contingent_business_interruption_limit": 2000000, "contingent_business_interruption_retention": 5000,
               "contingent_business_interruption_exposure_modifier": None,
               "contingent_business_interruption_probability_modifier": None, "contingent_business_interruption_pop_percentage": None,
               "system_failure_limit": 2000000, "system_failure_retention": 5000, "system_failure_exposure_modifier": 0.94,
               "system_failure_probability_modifier": 1.03, "system_failure_pop_percentage": None,
               "system_failure_waiting_period_parameter": 8, "direct_system_failure_limit": 2000000,
               "direct_system_failure_retention": 5000, "direct_system_failure_exposure_modifier": 0.94,
               "direct_system_failure_probability_modifier": 1.03, "direct_system_failure_pop_percentage": None,
               "direct_system_failure_waiting_period_parameter": 8, "contingent_system_failure_limit": 2000000,
               "contingent_system_failure_retention": 5000, "contingent_system_failure_exposure_modifier": None,
               "contingent_system_failure_probability_modifier": None, "contingent_system_failure_pop_percentage": None,
               "cyber_extortion_limit": 2000000, "cyber_extortion_retention": 5000, "cyber_extortion_exposure_modifier": 1.13,
               "cyber_extortion_probability_modifier": 1.07, "cyber_extortion_pop_percentage": None, "financial_fraud_limit": 250000,
               "financial_fraud_retention": 10000, "financial_fraud_exposure_modifier": 1,
               "financial_fraud_probability_modifier": 0.77, "financial_fraud_pop_percentage": None,
               "social_engineering_limit": 250000, "social_engineering_retention": 10000, "social_engineering_exposure_modifier": 1,
               "social_engineering_probability_modifier": 0.77, "social_engineering_pop_percentage": None,
               "computer_fraud_limit": 250000, "computer_fraud_retention": 10000, "computer_fraud_exposure_modifier": None,
               "computer_fraud_probability_modifier": None, "computer_fraud_pop_percentage": None, "media_content_limit": 2000000,
               "media_content_retention": 5000, "media_content_exposure_modifier": 1, "media_content_probability_modifier": 0.99,
               "media_content_pop_percentage": None, "media_liability_limit": 2000000, "media_liability_retention": 5000,
               "media_liability_exposure_modifier": 1, "media_liability_probability_modifier": 0.99,
               "media_liability_pop_percentage": None, "media_event_response_limit": 2000000, "media_event_response_retention": 5000,
               "media_event_response_exposure_modifier": None, "media_event_response_probability_modifier": None,
               "media_event_response_pop_percentage": None, "reputational_harm_limit": 2000000, "reputational_harm_retention": 5000,
               "reputational_harm_exposure_modifier": 1.19, "reputational_harm_probability_modifier": None,
               "reputational_harm_pop_percentage": None, "reputational_harm_period_of_indemnity_parameter": 180,
               "contingent_bodily_injury_limit": 250000, "contingent_bodily_injury_retention": 5000,
               "contingent_bodily_injury_exposure_modifier": 1.5, "contingent_bodily_injury_probability_modifier": None,
               "contingent_bodily_injury_pop_percentage": None, "invoice_manipulation_limit": None,
               "invoice_manipulation_retention": None, "invoice_manipulation_exposure_modifier": None,
               "invoice_manipulation_probability_modifier": None, "invoice_manipulation_pop_percentage": 0.05,
               "funds_transfer_fraud_limit": None, "funds_transfer_fraud_retention": None,
               "funds_transfer_fraud_exposure_modifier": None, "funds_transfer_fraud_probability_modifier": None,
               "funds_transfer_fraud_pop_percentage": 0.1, "cryptojacking_limit": None, "cryptojacking_retention": None,
               "cryptojacking_exposure_modifier": None, "cryptojacking_probability_modifier": None,
               "cryptojacking_pop_percentage": 0.05, "breach_costs_outside_limit": None, "breach_costs_outside_retention": None,
               "breach_costs_outside_exposure_modifier": None, "breach_costs_outside_probability_modifier": None,
               "breach_costs_outside_pop_percentage": 0.2, "commercial_consideration": 1, "operational_considerations": 0.9,
               "prior_acts_coverage": 1, "per_claim_limit": 2000000, "CA1": None, "CA10": None, "CA12": None, "CA13": None,
               "CA15": None, "CA17": None, "CA19": None, "CA2": None, "CA20": None, "CA21": None, "CA22": None, "CA24": None,
               "CA25": None, "CA26": None, "CA28": None, "CA29": None, "CA3": None, "CA30": None, "CA31": None, "CA4": None,
               "CA5": None, "CA6": None, "CA7": None, "CA8": None, "Ex1": 0, "Ex21": 0, "Ex22": 1, "Ex23": 24, "Ex24": 86, "Ex25": 31,
               "Ex28": 0, "Ex31": 122923952, "Ex32": 1, "Ex33": 0, "Ex34": 1, "Ex35": 1, "Ex36": 0, "Ex37": 0, "Ex38": 0, "Ex39": 0,
               "Ex40": 0, "Ex41": 0, "Ex42": 0, "Ex43": 0, "Ex44": 0, "Ex45": 0, "Ex51": 0, "Ex52": 0, "Ex53": 0, "Ex54": 0, "Ex55": 0,
               "Ex56": 229, "Ex57": 0, "Ex58": 0, "Ex59": True, "UW40": None, "UW41": "B2B", "UW42": None, "UW44": None, "UW50": None,
               "UW51": None, "UW52": None, "UW53": None, "UW54": None, "UW55": "True", "UW56": None, "UW57": None, "UW58": None,
               "UW59": None, "UW60": None, "UW61": False, "UW62": None, "UW63": None, "UW64": None, "UW65": None, "UW66": False,
               "UW67": None, "UW68": None, "UW69": None, "UW70": None, "UW71": None, "UW72": None, "UW73": None, "UW74": None,
               "UW75": "Below Average", "Q2119": None, "Q2124": None, "Q2135": "Test Ronit Cyber", "Q2136": 15000000,
               "Q2137": "9gag.com", "Q2138": "Retail Trade", "Q2140": None, "Q2141": True, "Q2142": True, "Q2143": False,
               "Q2146": False, "Q2147": False, "Q2159": True, "Q2162": None,
               "Q2163": "{\"formatted_address\": \"100 S Main St, Los Angeles, CA 90012, \\u05d0\\u05e8\\u05e6\\u05d5\\u05ea \\u05d4\\u05d1\\u05e8\\u05d9\\u05ea\"}",
               "Q2164": None, "Q2231": None, "Q2232": None, "Q2233": None, "Q2234": "Automobile Dealers", "Q2236": None, "Q2237": None,
               "Q2244_C1576": False, "Q2244_C1577": False, "Q2244_C1578": False, "Q2244_C1579": False, "Q2244_C1580": False,
               "Q2244_C1581": False, "Q2244_C1582": False, "Q2244_NONE_OF_THE_ABOVE": True, "Q2245": True}
